blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://community.home-assistant.io/t/llm-vision-let-home-assistant-see/729241
    about: Please ask and answer questions in the community. For more technical questions, post them in the discussion tab under 'Q&A'.
