image_analyzer:
  fields:
    provider:
      description: 'Select Provider'
      required: true
      default: 'OpenAI'
      selector:
        select:
          options:
            - 'OpenAI'
            - 'LocalAI'
            - 'Ollama'
    message:
      required: true
      description: 'Prompt'
      example: "Describe the person present in the photo"
      selector:
        text:
          multiline: true
    max_tokens:
      description: 'Maximum number of tokens to generate'
      required: true
      example: 100
      default: 100
      selector:
        number:
          min: 10
          max: 1000
    image_file:
      required: false
      description: 'The path to you image'
      example: "/config/www/images/img.jpg"
      selector:
        text:
          multiline: true
    image_entity:
      required: false
      description: 'Image entity you want to submit'
      example: 'image.front_door_person'
      selector:
        entity:
          domain: image
          multiple: true
    model:
      required: false
      description: 'Which model to use'
      example: "gpt-4o"
      default: "gpt-4o"
      selector:
        text:
          multiline: false
    target_width:
      required: false
      description: 'Width in pixels to downscale to'
      example: 1280
      default: 1280
      selector:
        number:
          min: 512
          max: 3840
    detail:
      required: false
      description: "Detail parameter (OpenAI only), leave empty for 'auto'"
      default: 'high'
      selector:
        select:
          options:
            - 'high'
            - 'low'
    temperature:
      required: true
      description: 'Randomness. Lower is more accurate, higher is more creative'
      example: 0.5
      default: 0.5
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.1